### Site metadata

title: DALE WHISTLER, ARTIST
description: A gallery of images for an artist's portfolio, built with Jekyll

url: "https://rectalogic.com/"

github_username: "MichaelCurrin"
repository: "MichaelCurrin/artists-portfolio"

google_analytics_key: ""

# For SEO tag.
logo: /siteicon.png
author:
  name: Dale Whistler
  twitter:
social:
  name: DALE WHISTLER, ARTIST
  links:
    - https://github.com/MichaelCurrin/artists-portfolio

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
